# Setup
name:             'ManuCiao'
first_name:       'Manuela'
last_name:        'Sabatino'
twitter_username:  MnlSabatino
github_username:   ManuCiao
facebook_username: manuciao8
linkedin_username: mnsabatino
title:             Geeky G-Blog
tagline:           'geeky g-blog'
email:             mn.sabatino@gmail.com
description:       The journey to get the life I Want..
baseurl:           "/"
url:               "http://ManuCiao.github.io"

author:
  name:            'Manuela Sabatino'
  url:             https://twitter.com/MnlSabatino

paginate:          5

# Custom vars
version:           2.0.0

# Build settings
 
# Dependencies
markdown:          kramdown
highlighter:       rouge

# Permalinks
permalink:         pretty

paginate:          5
paginate_path:     "page:num"

github:            https://github.com/ManuCiao
repo:              https://github.com/ManuCiao/ManuCiao.github.io.git

plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-gist

exclude:
- Gemfile
- Gemfile.lock